---
- name: Set Up manager
  hosts: manager
  remote_user: root
  roles:
    - swap
    - docker
    - certbot
    - jenkins

- name: Set Up agent
  hosts: manager
  remote_user: root
  roles:
    - swap
    - docker
    - java
    - agent
