---
- name: Upgrade
  hosts: all
  remote_user: root
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Upgrade APT to the latest packages
      apt:
        upgrade: dist

    - name: Remove useles packages
      apt:
        autoclean: yes

    - name: Remove useles dependencies
      apt:
        autoremove: yes
